# docker build -t whisper-webui --build-arg WHISPER_IMPLEMENTATION=fast-whisper -f dockerfile-whisper .

FROM python:3.10
EXPOSE 7860

ARG WHISPER_IMPLEMENTATION=whisper
ENV WHISPER_IMPLEMENTATION=${WHISPER_IMPLEMENTATION}

RUN git clone --depth 1 https://github.com/ericwang2006/whisper-webui.git /opt/whisper-webui/

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN  python3 -m pip install --upgrade pip

RUN if [ "${WHISPER_IMPLEMENTATION}" = "whisper" ]; then \
    python3 -m pip install -r /opt/whisper-webui/requirements-whisper.txt; \
  else \
    python3 -m pip install -r /opt/whisper-webui/requirements-fasterWhisper.txt; \
  fi

# To be able to see logs in real time
ENV PYTHONUNBUFFERED=1

WORKDIR /opt/whisper-webui/
ENTRYPOINT ["python3"]
CMD ["app.py", "--input_audio_max_duration", "-1", "--server_name", "0.0.0.0", "--auto_parallel", "True"]